services:
  mariadb:
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
     - data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception
    depends_on:
      - wordpress

  
    
networks:
  inception:
    driver: bridge

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aerraoui/data/database
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aerraoui/data/wordpress