`

services:
  nginx:
    container_name: nginx_container
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx_image
    depends_on:
      - wordpress
    ports:
      - "8000:8000"
    volumes:
      - ./www:/var/www/html
    networks:
      - net_test
  
  mariadb:
    container_name: mariadb_container
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    image: mariadb_image
    networks:
      - net_test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    volumes:
      - www:/var/lib/mysql
  wordpress:
    container_name: wordpress_container
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    image: wordpress_image
    depends_on:
      - mariadb
    networks:
      - net_test
    volumes:
      - ./www:/var/www/html
networks:
  net_test:
    driver: bridge

volumes:
  www:
    driver: local
    driver_opts:
      type: none
      device: /home/kali/Desktop/AYEMAN/www
      o: bind